---
title: "YTM Jan 17"
author: "Yuhao Guo"
date: "2023/2/2"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(stringr)
library(tidyverse)
```

```{r}
library(jrvFinance)
```

```{r}
data<-read.csv(file = "A1_Bond_data.csv", header = T)
```

```{r}
data_17 <- data %>%
  select(name, Coupon, days, c_since_days, c_next_days, Jan_17)

data_17<- data_17%>%
  mutate(dirty_price = (((c_since_days+1)/365)*100*Coupon) + Jan_17,
         FV=100 + 0.5*100*Coupon)

```

```{r}
c_1 = 0.5*data_17$Coupon[1]*100
cash_flow_1 = c(-data_17$dirty_price[1], data_17$FV[1])
payment_time_1 = c(0, (data_17$days[1]-1)/365 )
irr(cf = cash_flow_1, cf.t = payment_time_1)
```
```{r}
t_2 = (data_17$c_next_days[2] - 1)/365
c_2 = 0.5*data_17$Coupon[2]*100
cash_flow_2 = c(-data_17$dirty_price[2], c_2, data_17$FV[2])
payment_time_2 = c(0, t_2, (data_17$days[2]-1)/365 )
irr(cf = cash_flow_2, cf.t = payment_time_2)
```
```{r}
t_3 = (data_17$c_next_days[3] - 1)/365
c_3 = 0.5*data_17$Coupon[3]*100
cash_flow_3 = c(-data_17$dirty_price[3],c_3,c_3, data_17$FV[3])
payment_time_3 = c(0, t_3, t_3+0.5, (data_17$days[3]-1)/365 )
irr(cf = cash_flow_3, cf.t = payment_time_3)
```
```{r}
t_4 = (data_17$c_next_days[4] -1)/365
c_4 = 0.5*data_17$Coupon[4]*100
cash_flow_4 = c(-data_17$dirty_price[4],c_4,c_4,c_4, data_17$FV[4])
payment_time_4 = c(0, t_4,t_4+0.5,t_4+1, (data_17$days[4]-1)/365 )
irr(cf = cash_flow_4, cf.t = payment_time_4)
```
```{r}
t_5 = (data_17$c_next_days[5] - 1)/365
c_5 = 0.5*data_17$Coupon[5]*100
cash_flow_5 = c(-data_17$dirty_price[5],c_5, c_5 ,c_5,c_5, data_17$FV[5])
payment_time_5 = c(0, t_5,t_5+0.5,t_5+1,t_5+1.5, (data_17$days[5]-1)/365 )
irr(cf=cash_flow_5, cf.t=payment_time_5)
```
```{r}
t_6 = (data_17$c_next_days[6]-1)/365
c_6 = 0.5*data_17$Coupon[6]*100
cash_flow_6 = c(-data_17$dirty_price[6],c_6, c_6 ,c_6,c_6,c_6, data_17$FV[6])
payment_time_6 = c(0, t_6,t_6+0.5,t_6+1,t_6+1.5, t_6+2, (data_17$days[6]-1)/365 )
irr(cf=cash_flow_6, cf.t=payment_time_6)
```
```{r}
t_7 = (data_17$c_next_days[7]-1)/365
c_7 = 0.5*data_17$Coupon[7]*100
cash_flow_7 = c(-data_17$dirty_price[7],c_7, c_7 ,c_7,c_7,c_7,c_7, data_17$FV[7])
payment_time_7 = c(0, t_7,t_7+0.5, t_7+1, t_7+1.5,t_7+2,t_7+2.5, (data_17$days[7]-1)/365 )
irr(cf=cash_flow_7, cf.t=payment_time_7)
```


```{r}
t_8 = (data_17$c_next_days[8] - 1)/365
c_8 = 0.5*data_17$Coupon[8]*100
cash_flow_8 = c(-data_17$dirty_price[8],c_8, c_8 ,c_8,c_8,c_8,c_8,c_8, data_17$FV[8])
payment_time_8 = c(0, t_8,t_8+0.5, t_8+1, t_8+1.5,t_8+2, t_8+2.5,t_8+3, (data_17$days[8]-1)/365 )
irr(cf=cash_flow_8, cf.t=payment_time_8)
```
```{r}
t_9 = (data_17$c_next_days[9] - 1)/365
c_9 = 0.5*data_17$Coupon[9]*100
cash_flow_9 = c(-data_17$dirty_price[9],c_9, c_9 ,c_9,c_9,c_9,c_9,c_9,c_9,data_17$FV[9])
payment_time_9 = c(0, t_9,t_9+0.5, t_9+1, t_9+1.5,t_9+2, t_9+2.5,t_9+3,t_9+3.5, (data_17$days[9]-1)/365 )
irr(cf=cash_flow_9, cf.t=payment_time_9)
```
```{r}
t_10 = (data_17$c_next_days[10]-1)/365
c_10 = 0.5*data_17$Coupon[10]*100
cash_flow_10 = c(-data_17$dirty_price[10],c_10, c_10 ,c_10,c_10,c_10,c_10,c_10,c_10, c_10,data_17$FV[10])
payment_time_10 = c(0, t_10,t_10+0.5, t_10+1, t_10+1.5,t_10+2, t_10+2.5,t_10+3,t_10+3.5,t_10+4, (data_17$days[10]-1)/365 )
irr(cf=cash_flow_10, cf.t=payment_time_10)
```
```{r}
t_11 = (data_17$c_next_days[11] - 1)/365
c_11 = 0.5*data_17$Coupon[11]*100
cash_flow_11 = c(-data_17$dirty_price[11],c_11, c_11 ,c_11,c_11,c_11,c_11,c_11,c_11, c_11, c_11,data_17$FV[11])
payment_time_11 = c(0, t_11,t_11+0.5, t_11+1, t_11+1.5,t_11+2, t_11+2.5,t_11+3,t_11+3.5,t_11+4,t_11+4.5, (data_17$days[11] - 1)/365 )
irr(cf=cash_flow_11, cf.t=payment_time_11)
```


